//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resume_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int IDCer { get; set; }
        public int IdPers { get; set; }
        public string CertificationName { get; set; }
        public string LastName { get; set; }
        public string LevelCertification { get; set; }
        public System.DateTime FromYear { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
